kuiper:
  image:                            # Registry to pull the Kuiper server image from
  namespace: production             # Namespace to deploy the Kuiper server to

  node_selector:                   # Node selector to deploy the Kuiper server to
    enable: true                   # Enable node selector
    labels:                        # Node selector to deploy the Kuiper server to
      kubernetes.io/arch: amd64


  autoscaling:
    min_replicas: 1                 # Minimum number of replicas to run
    max_replicas: 3                 # Maximum number of replicas to run

  workstations:                     # List of workstation templates to deploy
#    - registry:                    # Registry to pull the workstation image from
#      icon:                        # Icon to display for the workstation
#      label:                       # Label to display for the workstation
#      group:                       # Group to display the workstation under
#      tag:                         # Tag to pull the workstation image from
#      repo:                        # Repository to pull the workstation image from
#      cpu:                         # CPU to allocate to the workstation
#      ram:                         # RAM to allocate to the workstation
#      name:                        # Name of the workstation
#      gpu:                         # GPU to allocate to the workstation
